version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://backend:8000
        VITE_NODE_ENV: production
    container_name: frontend
    # image: adamilkom00/frontend:0.0.1
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge