version: '3.8'

services:
  backend:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    container_name: backend
    image: adamilkom00/decision_tree_backend:0.0.6
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app-network
    extra_hosts:
      - "remote-db:172.16.20.142"
    environment:
      - DATABASE_URL=mysql+pymysql://sibea:s1b34unp4kAPPS@remote-db:3306/unpak_sibea

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://sibea.unpak.ac.id/api/
        VITE_NODE_ENV: production
    container_name: frontend
    image: adamilkom00/decision_tree_frontend:0.0.2
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=https://sibea.unpak.ac.id/api/
      - VITE_NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge